# Параметры рекордера
SAMPLE_RATE = 16000  # Количество бит на 1 секунду
BLOCK_SIZE = 1024
CHUNK_SECONDS = 5
DEVICE = "Микрофон (5- fifine Microphone), MME"

# Параметры транскрибера
WAKE_WORD_REGEX = "леха|лёха|алеха|алёха"

SPEECH_RECOGNITION_THRESHOLD = 0.7

MAX_COMMAND_DURATION_SECONDS = 10
MAX_SILENCE_DURATION_SECONDS = 2

WINDOW_LENGTH_SECONDS = 2.0
WINDOW = int(SAMPLE_RATE * WINDOW_LENGTH_SECONDS)

CHECK_WAKE_EVERY_SECONDS = 0.25
HOP = int(SAMPLE_RATE * CHECK_WAKE_EVERY_SECONDS)

LARGE_AUDIO_BUFFER_SIZE = int(SAMPLE_RATE * MAX_COMMAND_DURATION_SECONDS)